/*
 * Video Analytic Guidance Solution - Video Logistics
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-10-18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.videoanalytics.videologistics;

import java.util.Objects;
import com.amazonaws.videoanalytics.videologistics.Timeline;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.amazonaws.videoanalytics.JSON;

/**
 * DetailedVideoTimeline
 */
@lombok.Builder
@lombok.AllArgsConstructor
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class DetailedVideoTimeline {
  public static final String SERIALIZED_NAME_CLOUD = "cloud";
  @SerializedName(SERIALIZED_NAME_CLOUD)
  private List<Timeline> cloud = new ArrayList<>();

  public static final String SERIALIZED_NAME_DEVICE = "device";
  @SerializedName(SERIALIZED_NAME_DEVICE)
  private List<Timeline> device = new ArrayList<>();

  public DetailedVideoTimeline() {
  }

  public DetailedVideoTimeline cloud(List<Timeline> cloud) {
    this.cloud = cloud;
    return this;
  }

  public DetailedVideoTimeline addCloudItem(Timeline cloudItem) {
    if (this.cloud == null) {
      this.cloud = new ArrayList<>();
    }
    this.cloud.add(cloudItem);
    return this;
  }

  /**
   * Get cloud
   * @return cloud
   */
  @javax.annotation.Nullable
  public List<Timeline> getCloud() {
    return cloud;
  }

  public void setCloud(List<Timeline> cloud) {
    this.cloud = cloud;
  }


  public DetailedVideoTimeline device(List<Timeline> device) {
    this.device = device;
    return this;
  }

  public DetailedVideoTimeline addDeviceItem(Timeline deviceItem) {
    if (this.device == null) {
      this.device = new ArrayList<>();
    }
    this.device.add(deviceItem);
    return this;
  }

  /**
   * Get device
   * @return device
   */
  @javax.annotation.Nullable
  public List<Timeline> getDevice() {
    return device;
  }

  public void setDevice(List<Timeline> device) {
    this.device = device;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DetailedVideoTimeline detailedVideoTimeline = (DetailedVideoTimeline) o;
    return Objects.equals(this.cloud, detailedVideoTimeline.cloud) &&
        Objects.equals(this.device, detailedVideoTimeline.device);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cloud, device);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DetailedVideoTimeline {\n");
    sb.append("    cloud: ").append(toIndentedString(cloud)).append("\n");
    sb.append("    device: ").append(toIndentedString(device)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cloud");
    openapiFields.add("device");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DetailedVideoTimeline
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DetailedVideoTimeline.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DetailedVideoTimeline is not found in the empty JSON string", DetailedVideoTimeline.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DetailedVideoTimeline.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DetailedVideoTimeline` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("cloud") != null && !jsonObj.get("cloud").isJsonNull()) {
        JsonArray jsonArraycloud = jsonObj.getAsJsonArray("cloud");
        if (jsonArraycloud != null) {
          // ensure the json data is an array
          if (!jsonObj.get("cloud").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `cloud` to be an array in the JSON string but got `%s`", jsonObj.get("cloud").toString()));
          }

          // validate the optional field `cloud` (array)
          for (int i = 0; i < jsonArraycloud.size(); i++) {
            Timeline.validateJsonElement(jsonArraycloud.get(i));
          };
        }
      }
      if (jsonObj.get("device") != null && !jsonObj.get("device").isJsonNull()) {
        JsonArray jsonArraydevice = jsonObj.getAsJsonArray("device");
        if (jsonArraydevice != null) {
          // ensure the json data is an array
          if (!jsonObj.get("device").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `device` to be an array in the JSON string but got `%s`", jsonObj.get("device").toString()));
          }

          // validate the optional field `device` (array)
          for (int i = 0; i < jsonArraydevice.size(); i++) {
            Timeline.validateJsonElement(jsonArraydevice.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DetailedVideoTimeline.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DetailedVideoTimeline' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DetailedVideoTimeline> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DetailedVideoTimeline.class));

       return (TypeAdapter<T>) new TypeAdapter<DetailedVideoTimeline>() {
           @Override
           public void write(JsonWriter out, DetailedVideoTimeline value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DetailedVideoTimeline read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DetailedVideoTimeline given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DetailedVideoTimeline
   * @throws IOException if the JSON string is invalid with respect to DetailedVideoTimeline
   */
  public static DetailedVideoTimeline fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DetailedVideoTimeline.class);
  }

  /**
   * Convert an instance of DetailedVideoTimeline to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

