/*
 * Video Analytic Guidance Solution - Video Logistics
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-10-18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.videoanalytics.videologistics;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.amazonaws.videoanalytics.JSON;

/**
 * KVSStreamARNs
 */
@lombok.Builder
@lombok.AllArgsConstructor
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class KVSStreamARNs {
  public static final String SERIALIZED_NAME_KVS_STREAM_A_R_N_FOR_PLAYBACK = "kvsStreamARNForPlayback";
  @SerializedName(SERIALIZED_NAME_KVS_STREAM_A_R_N_FOR_PLAYBACK)
  private String kvsStreamARNForPlayback;

  public KVSStreamARNs() {
  }

  public KVSStreamARNs kvsStreamARNForPlayback(String kvsStreamARNForPlayback) {
    this.kvsStreamARNForPlayback = kvsStreamARNForPlayback;
    return this;
  }

  /**
   * Get kvsStreamARNForPlayback
   * @return kvsStreamARNForPlayback
   */
  @javax.annotation.Nullable
  public String getKvsStreamARNForPlayback() {
    return kvsStreamARNForPlayback;
  }

  public void setKvsStreamARNForPlayback(String kvsStreamARNForPlayback) {
    this.kvsStreamARNForPlayback = kvsStreamARNForPlayback;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KVSStreamARNs kvSStreamARNs = (KVSStreamARNs) o;
    return Objects.equals(this.kvsStreamARNForPlayback, kvSStreamARNs.kvsStreamARNForPlayback);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kvsStreamARNForPlayback);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KVSStreamARNs {\n");
    sb.append("    kvsStreamARNForPlayback: ").append(toIndentedString(kvsStreamARNForPlayback)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("kvsStreamARNForPlayback");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to KVSStreamARNs
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!KVSStreamARNs.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in KVSStreamARNs is not found in the empty JSON string", KVSStreamARNs.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!KVSStreamARNs.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `KVSStreamARNs` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("kvsStreamARNForPlayback") != null && !jsonObj.get("kvsStreamARNForPlayback").isJsonNull()) && !jsonObj.get("kvsStreamARNForPlayback").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `kvsStreamARNForPlayback` to be a primitive type in the JSON string but got `%s`", jsonObj.get("kvsStreamARNForPlayback").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!KVSStreamARNs.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'KVSStreamARNs' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<KVSStreamARNs> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(KVSStreamARNs.class));

       return (TypeAdapter<T>) new TypeAdapter<KVSStreamARNs>() {
           @Override
           public void write(JsonWriter out, KVSStreamARNs value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public KVSStreamARNs read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of KVSStreamARNs given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of KVSStreamARNs
   * @throws IOException if the JSON string is invalid with respect to KVSStreamARNs
   */
  public static KVSStreamARNs fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, KVSStreamARNs.class);
  }

  /**
   * Convert an instance of KVSStreamARNs to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

