/*
 * Video Analytic Guidance Solution - Video Logistics
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-10-18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.videoanalytics.videologistics;

import java.util.Objects;
import com.amazonaws.videoanalytics.videologistics.DetailedVideoTimeline;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.amazonaws.videoanalytics.JSON;

/**
 * ListDetailedVideoTimelineResponseContent
 */
@lombok.Builder
@lombok.AllArgsConstructor
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.8.0")
public class ListDetailedVideoTimelineResponseContent {
  public static final String SERIALIZED_NAME_DEVICE_ID = "deviceId";
  @SerializedName(SERIALIZED_NAME_DEVICE_ID)
  private String deviceId;

  public static final String SERIALIZED_NAME_START_TIME = "startTime";
  @SerializedName(SERIALIZED_NAME_START_TIME)
  private Double startTime;

  public static final String SERIALIZED_NAME_END_TIME = "endTime";
  @SerializedName(SERIALIZED_NAME_END_TIME)
  private Double endTime;

  public static final String SERIALIZED_NAME_DETAILED_VIDEO_TIMELINE = "detailedVideoTimeline";
  @SerializedName(SERIALIZED_NAME_DETAILED_VIDEO_TIMELINE)
  private DetailedVideoTimeline detailedVideoTimeline;

  public static final String SERIALIZED_NAME_NEXT_TOKEN = "nextToken";
  @SerializedName(SERIALIZED_NAME_NEXT_TOKEN)
  private String nextToken;

  public ListDetailedVideoTimelineResponseContent() {
  }

  public ListDetailedVideoTimelineResponseContent deviceId(String deviceId) {
    this.deviceId = deviceId;
    return this;
  }

  /**
   * Get deviceId
   * @return deviceId
   */
  @javax.annotation.Nullable
  public String getDeviceId() {
    return deviceId;
  }

  public void setDeviceId(String deviceId) {
    this.deviceId = deviceId;
  }


  public ListDetailedVideoTimelineResponseContent startTime(Double startTime) {
    this.startTime = startTime;
    return this;
  }

  /**
   * Get startTime
   * @return startTime
   */
  @javax.annotation.Nullable
  public Double getStartTime() {
    return startTime;
  }

  public void setStartTime(Double startTime) {
    this.startTime = startTime;
  }


  public ListDetailedVideoTimelineResponseContent endTime(Double endTime) {
    this.endTime = endTime;
    return this;
  }

  /**
   * Get endTime
   * @return endTime
   */
  @javax.annotation.Nullable
  public Double getEndTime() {
    return endTime;
  }

  public void setEndTime(Double endTime) {
    this.endTime = endTime;
  }


  public ListDetailedVideoTimelineResponseContent detailedVideoTimeline(DetailedVideoTimeline detailedVideoTimeline) {
    this.detailedVideoTimeline = detailedVideoTimeline;
    return this;
  }

  /**
   * Get detailedVideoTimeline
   * @return detailedVideoTimeline
   */
  @javax.annotation.Nullable
  public DetailedVideoTimeline getDetailedVideoTimeline() {
    return detailedVideoTimeline;
  }

  public void setDetailedVideoTimeline(DetailedVideoTimeline detailedVideoTimeline) {
    this.detailedVideoTimeline = detailedVideoTimeline;
  }


  public ListDetailedVideoTimelineResponseContent nextToken(String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

  /**
   * Get nextToken
   * @return nextToken
   */
  @javax.annotation.Nullable
  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(String nextToken) {
    this.nextToken = nextToken;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListDetailedVideoTimelineResponseContent listDetailedVideoTimelineResponseContent = (ListDetailedVideoTimelineResponseContent) o;
    return Objects.equals(this.deviceId, listDetailedVideoTimelineResponseContent.deviceId) &&
        Objects.equals(this.startTime, listDetailedVideoTimelineResponseContent.startTime) &&
        Objects.equals(this.endTime, listDetailedVideoTimelineResponseContent.endTime) &&
        Objects.equals(this.detailedVideoTimeline, listDetailedVideoTimelineResponseContent.detailedVideoTimeline) &&
        Objects.equals(this.nextToken, listDetailedVideoTimelineResponseContent.nextToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceId, startTime, endTime, detailedVideoTimeline, nextToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListDetailedVideoTimelineResponseContent {\n");
    sb.append("    deviceId: ").append(toIndentedString(deviceId)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    detailedVideoTimeline: ").append(toIndentedString(detailedVideoTimeline)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("deviceId");
    openapiFields.add("startTime");
    openapiFields.add("endTime");
    openapiFields.add("detailedVideoTimeline");
    openapiFields.add("nextToken");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListDetailedVideoTimelineResponseContent
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListDetailedVideoTimelineResponseContent.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListDetailedVideoTimelineResponseContent is not found in the empty JSON string", ListDetailedVideoTimelineResponseContent.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListDetailedVideoTimelineResponseContent.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListDetailedVideoTimelineResponseContent` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("deviceId") != null && !jsonObj.get("deviceId").isJsonNull()) && !jsonObj.get("deviceId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `deviceId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("deviceId").toString()));
      }
      // validate the optional field `detailedVideoTimeline`
      if (jsonObj.get("detailedVideoTimeline") != null && !jsonObj.get("detailedVideoTimeline").isJsonNull()) {
        DetailedVideoTimeline.validateJsonElement(jsonObj.get("detailedVideoTimeline"));
      }
      if ((jsonObj.get("nextToken") != null && !jsonObj.get("nextToken").isJsonNull()) && !jsonObj.get("nextToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nextToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nextToken").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListDetailedVideoTimelineResponseContent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListDetailedVideoTimelineResponseContent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListDetailedVideoTimelineResponseContent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListDetailedVideoTimelineResponseContent.class));

       return (TypeAdapter<T>) new TypeAdapter<ListDetailedVideoTimelineResponseContent>() {
           @Override
           public void write(JsonWriter out, ListDetailedVideoTimelineResponseContent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListDetailedVideoTimelineResponseContent read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListDetailedVideoTimelineResponseContent given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListDetailedVideoTimelineResponseContent
   * @throws IOException if the JSON string is invalid with respect to ListDetailedVideoTimelineResponseContent
   */
  public static ListDetailedVideoTimelineResponseContent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListDetailedVideoTimelineResponseContent.class);
  }

  /**
   * Convert an instance of ListDetailedVideoTimelineResponseContent to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

