/*
 * Video Analytic Guidance Solution - Video Logistics
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-10-18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.videoanalytics.videologistics;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PeerConnectionState
 */
@JsonAdapter(PeerConnectionState.Adapter.class)
public enum PeerConnectionState {
  
  PENDING("Pending"),
  
  CONNECTING("Connecting"),
  
  CONNECTED("Connected"),
  
  DISCONNECTED("Disconnected"),
  
  FAILED("Failed");

  private String value;

  PeerConnectionState(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PeerConnectionState fromValue(String value) {
    for (PeerConnectionState b : PeerConnectionState.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PeerConnectionState> {
    @Override
    public void write(final JsonWriter jsonWriter, final PeerConnectionState enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PeerConnectionState read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PeerConnectionState.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    PeerConnectionState.fromValue(value);
  }
}

