export const CLE_SERVICE_ROLE_PREFIX = 'CoralLambdaEndpointServiceRole';
export const PAGINATION_KEY_ALIAS = 'alias/PaginationSymmetricKey';
export const FAS_ENCRYPTION_KEY_ALIAS = 'alias/FASEncryptionSymmetricKey';
export const FAS_ENCRYPTION_KEY_ID = 'FASEncryptionSymmetricKey';
export const JOB_ID = 'JobId';
export const LAMBDA_SERVICE_PRINCIPAL = 'lambda.amazonaws.com';
export const LAMBDA_MANAGED_POLICY_NAME = 'service-role/AWSLambdaBasicExecutionRole';
export const INTEGRATION_TEST_STATE_NOTIFICATIONS_QUEUE = 'StateNotificationIntegrationTestQueue';
export const DEFAULT_LAMBDA_PACKAGE_NAME = 'placeholder';//TODO: replace with actual value
export const DEFAULT_LAMBDA_HANDLER_DIRECTORY = 'com.amazonaws.services.lambda.placeholder';//TODO: replace with actual value
