package com.amazonaws.videoanalytics.devicemanagement.schema;

import com.amazonaws.videoanalytics.devicemanagement.schema.SchemaConst;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbUpdateBehavior;
import software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSecondaryPartitionKey;

import java.time.Instant;

@DynamoDbBean
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Data
public class CreateDevice {
    @Getter(onMethod_ = { @DynamoDbPartitionKey, @DynamoDbAttribute(SchemaConst.JOB_ID) })
    private String jobId;

    @Getter(onMethod_ = { @DynamoDbAttribute(SchemaConst.DEVICE_ID),
            @DynamoDbSecondaryPartitionKey(indexNames = {"deviceId-index"}) })
    private String deviceId;

    @Getter(onMethod_ = { @DynamoDbAttribute(SchemaConst.CERTIFICATE_ID) })
    private String certificateId;

    @Getter(onMethod_ = { @DynamoDbAttribute(SchemaConst.JOB_STATUS) })
    private String jobStatus;

    @Getter(onMethod_ = { @DynamoDbAttribute(SchemaConst.ERROR_MESSAGE) })
    private String errorMessage;

    // Automatically updates attribute on save, only works on top level attributes
    @Getter(onMethod_ = { @DynamoDbAttribute(SchemaConst.LAST_UPDATED),
            @DynamoDbAutoGeneratedTimestampAttribute, @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_ALWAYS) })
    private Instant lastUpdated;

    // Automatically updates attribute on dynamo creation, only works on top level attributes
    @Getter(onMethod_ = { @DynamoDbAttribute(SchemaConst.CREATED_AT),
            @DynamoDbAutoGeneratedTimestampAttribute, @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS) })
    private Instant createdAt;

    @Getter(onMethod_ = { @DynamoDbAttribute(SchemaConst.WORKFLOW_NAME) })
    private String workflowName;

    // Job ID for the Video Logicstics workflow
    @Getter(onMethod_ = { @DynamoDbAttribute(SchemaConst.VL_JOB_ID) })
    private String vlJobId;

    // Job Status for the Video Logicstics workflow
    @Getter(onMethod_ = { @DynamoDbAttribute(SchemaConst.VL_JOB_STATUS) })
    private String vlJobStatus;

    @Getter(onMethod_ = { @DynamoDbAttribute(SchemaConst.CURRENT_DEVICE_STATE)})
    private String currentDeviceState;
}
