// GRCOV_STOP_COVERAGE
// Suppress linter warnings for autogenerated files.
#![allow(missing_docs, non_snake_case)]

use yaserde_derive::{YaDeserialize, YaSerialize};

/// onvif version
#[derive(Default, PartialEq, Debug, YaSerialize, YaDeserialize)]
#[yaserde(prefix = "tt", namespace = "tt: http://www.onvif.org/ver10/schema")]
pub struct OnvifVersion {
    /// Major version number.
    #[yaserde(prefix = "tt", rename = "Major")]
    pub major: i32,

    /// Two digit minor version number.
    /// If major version number is less than "16", X.0.1 maps to "01" and X.2.1
    /// maps to "21" where X stands for Major version number.
    /// Otherwise, minor number is month of release, such as "06" for June.
    #[yaserde(prefix = "tt", rename = "Minor")]
    pub minor: i32,
}
