/*
 * Video Analytic Guidance Solution - Device Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-10-18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.videoanalytics.devicemanagement;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.amazonaws.videoanalytics.JSON;

/**
 * DeviceGroupPayload
 */
@lombok.Builder
@lombok.AllArgsConstructor
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-01T14:43:28.076578-05:00[America/Chicago]", comments = "Generator version: 7.8.0")
public class DeviceGroupPayload {
  public static final String SERIALIZED_NAME_DEVICE_GROUP_ID_LIST = "deviceGroupIdList";
  @SerializedName(SERIALIZED_NAME_DEVICE_GROUP_ID_LIST)
  private List<String> deviceGroupIdList = new ArrayList<>();

  public static final String SERIALIZED_NAME_REMOVE = "remove";
  @SerializedName(SERIALIZED_NAME_REMOVE)
  private Boolean remove;

  public DeviceGroupPayload() {
  }

  public DeviceGroupPayload deviceGroupIdList(List<String> deviceGroupIdList) {
    this.deviceGroupIdList = deviceGroupIdList;
    return this;
  }

  public DeviceGroupPayload addDeviceGroupIdListItem(String deviceGroupIdListItem) {
    if (this.deviceGroupIdList == null) {
      this.deviceGroupIdList = new ArrayList<>();
    }
    this.deviceGroupIdList.add(deviceGroupIdListItem);
    return this;
  }

  /**
   * Get deviceGroupIdList
   * @return deviceGroupIdList
   */
  @javax.annotation.Nullable
  public List<String> getDeviceGroupIdList() {
    return deviceGroupIdList;
  }

  public void setDeviceGroupIdList(List<String> deviceGroupIdList) {
    this.deviceGroupIdList = deviceGroupIdList;
  }


  public DeviceGroupPayload remove(Boolean remove) {
    this.remove = remove;
    return this;
  }

  /**
   * Get remove
   * @return remove
   */
  @javax.annotation.Nullable
  public Boolean getRemove() {
    return remove;
  }

  public void setRemove(Boolean remove) {
    this.remove = remove;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeviceGroupPayload deviceGroupPayload = (DeviceGroupPayload) o;
    return Objects.equals(this.deviceGroupIdList, deviceGroupPayload.deviceGroupIdList) &&
        Objects.equals(this.remove, deviceGroupPayload.remove);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deviceGroupIdList, remove);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeviceGroupPayload {\n");
    sb.append("    deviceGroupIdList: ").append(toIndentedString(deviceGroupIdList)).append("\n");
    sb.append("    remove: ").append(toIndentedString(remove)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("deviceGroupIdList");
    openapiFields.add("remove");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DeviceGroupPayload
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DeviceGroupPayload.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DeviceGroupPayload is not found in the empty JSON string", DeviceGroupPayload.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DeviceGroupPayload.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DeviceGroupPayload` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("deviceGroupIdList") != null && !jsonObj.get("deviceGroupIdList").isJsonNull() && !jsonObj.get("deviceGroupIdList").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `deviceGroupIdList` to be an array in the JSON string but got `%s`", jsonObj.get("deviceGroupIdList").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DeviceGroupPayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DeviceGroupPayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DeviceGroupPayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DeviceGroupPayload.class));

       return (TypeAdapter<T>) new TypeAdapter<DeviceGroupPayload>() {
           @Override
           public void write(JsonWriter out, DeviceGroupPayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DeviceGroupPayload read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DeviceGroupPayload given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DeviceGroupPayload
   * @throws IOException if the JSON string is invalid with respect to DeviceGroupPayload
   */
  public static DeviceGroupPayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DeviceGroupPayload.class);
  }

  /**
   * Convert an instance of DeviceGroupPayload to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

