/*
 * Video Analytic Guidance Solution - Device Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-10-18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.videoanalytics.devicemanagement;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets StorageState
 */
@JsonAdapter(StorageState.Adapter.class)
public enum StorageState {
  
  NO_CARD("NO_CARD"),
  
  ERROR("ERROR"),
  
  NOT_FORMATTED("NOT_FORMATTED"),
  
  UNMOUNTED("UNMOUNTED"),
  
  FULL("FULL"),
  
  NORMAL("NORMAL");

  private String value;

  StorageState(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static StorageState fromValue(String value) {
    for (StorageState b : StorageState.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<StorageState> {
    @Override
    public void write(final JsonWriter jsonWriter, final StorageState enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public StorageState read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return StorageState.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    StorageState.fromValue(value);
  }
}

