/*
 * Video Analytic Guidance Solution - Device Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-10-18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.videoanalytics.devicemanagement;

import java.util.Objects;
import com.amazonaws.videoanalytics.devicemanagement.ShadowMap;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.amazonaws.videoanalytics.JSON;

/**
 * UpdateDeviceRequestContent
 */
@lombok.Builder
@lombok.AllArgsConstructor
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-01T14:43:28.076578-05:00[America/Chicago]", comments = "Generator version: 7.8.0")
public class UpdateDeviceRequestContent {
  public static final String SERIALIZED_NAME_ATTRIBUTE_PAYLOAD = "attributePayload";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTE_PAYLOAD)
  private Map<String, String> attributePayload = new HashMap<>();

  public static final String SERIALIZED_NAME_SHADOW_PAYLOAD = "shadowPayload";
  @SerializedName(SERIALIZED_NAME_SHADOW_PAYLOAD)
  private ShadowMap shadowPayload;

  public UpdateDeviceRequestContent() {
  }

  public UpdateDeviceRequestContent attributePayload(Map<String, String> attributePayload) {
    this.attributePayload = attributePayload;
    return this;
  }

  public UpdateDeviceRequestContent putAttributePayloadItem(String key, String attributePayloadItem) {
    if (this.attributePayload == null) {
      this.attributePayload = new HashMap<>();
    }
    this.attributePayload.put(key, attributePayloadItem);
    return this;
  }

  /**
   * Get attributePayload
   * @return attributePayload
   */
  @javax.annotation.Nullable
  public Map<String, String> getAttributePayload() {
    return attributePayload;
  }

  public void setAttributePayload(Map<String, String> attributePayload) {
    this.attributePayload = attributePayload;
  }


  public UpdateDeviceRequestContent shadowPayload(ShadowMap shadowPayload) {
    this.shadowPayload = shadowPayload;
    return this;
  }

  /**
   * Get shadowPayload
   * @return shadowPayload
   */
  @javax.annotation.Nullable
  public ShadowMap getShadowPayload() {
    return shadowPayload;
  }

  public void setShadowPayload(ShadowMap shadowPayload) {
    this.shadowPayload = shadowPayload;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateDeviceRequestContent updateDeviceRequestContent = (UpdateDeviceRequestContent) o;
    return Objects.equals(this.attributePayload, updateDeviceRequestContent.attributePayload) &&
        Objects.equals(this.shadowPayload, updateDeviceRequestContent.shadowPayload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributePayload, shadowPayload);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateDeviceRequestContent {\n");
    sb.append("    attributePayload: ").append(toIndentedString(attributePayload)).append("\n");
    sb.append("    shadowPayload: ").append(toIndentedString(shadowPayload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("attributePayload");
    openapiFields.add("shadowPayload");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateDeviceRequestContent
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateDeviceRequestContent.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateDeviceRequestContent is not found in the empty JSON string", UpdateDeviceRequestContent.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateDeviceRequestContent.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateDeviceRequestContent` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `shadowPayload`
      if (jsonObj.get("shadowPayload") != null && !jsonObj.get("shadowPayload").isJsonNull()) {
        ShadowMap.validateJsonElement(jsonObj.get("shadowPayload"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateDeviceRequestContent.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateDeviceRequestContent' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateDeviceRequestContent> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateDeviceRequestContent.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateDeviceRequestContent>() {
           @Override
           public void write(JsonWriter out, UpdateDeviceRequestContent value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateDeviceRequestContent read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateDeviceRequestContent given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateDeviceRequestContent
   * @throws IOException if the JSON string is invalid with respect to UpdateDeviceRequestContent
   */
  public static UpdateDeviceRequestContent fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateDeviceRequestContent.class);
  }

  /**
   * Convert an instance of UpdateDeviceRequestContent to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

