/*
 * Video Analytic Guidance Solution - Device Management
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-10-18
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.amazonaws.videoanalytics.devicemanagement;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ValidationExceptionReason
 */
@JsonAdapter(ValidationExceptionReason.Adapter.class)
public enum ValidationExceptionReason {
  
  UNKNOWN_OPERATION("unknownOperation"),
  
  CANNOT_PARSE("cannotParse"),
  
  FIELD_VALIDATION_FAILED("fieldValidationFailed"),
  
  OTHER("other");

  private String value;

  ValidationExceptionReason(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ValidationExceptionReason fromValue(String value) {
    for (ValidationExceptionReason b : ValidationExceptionReason.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ValidationExceptionReason> {
    @Override
    public void write(final JsonWriter jsonWriter, final ValidationExceptionReason enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ValidationExceptionReason read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ValidationExceptionReason.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ValidationExceptionReason.fromValue(value);
  }
}

